pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'cd ./Application && docker build ./App -t "img-app" && docker compose build'
      }
    }
    stage('Deploy') {
      steps {
        sh 'cd ./Application && docker compose down && docker container prune && docker compose up -d'
      }
    }
    stage('SBOM') {
      steps {
        sh 'syft app >> sbom.txt'
      }
    }

    stage ('OWASP Dependency-Check Vulnerabilities') {
        steps {
          dependencyCheck additionalArguments: '--format HTML', odcInstallation: 'owaspdpcheck'
      }
    }  
    
  }
}