pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'cd ./Application && docker compose build'
      }
    }
    stage('Deploy') {
      steps {
        sh 'cd ./Application && docker compose down && docker container prune && docker compose up -d'
      }
    }
  }
}